# Generated by Django 5.0.7 on 2024-08-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_remove_category_creationat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, db_index=True, default=1, null=True),
        ),
    ]
